### PR TITLE
Sync

### LINKED ISSUE #5: Move to sodium-universal - sync!
This is a bigger task, but this system needs to start using sodium-universal and syncronous crypto to fit better in the eco-system. for example: we could have a `valueEncoding` for hypercores but those methods are syncronous so we can not use our encryption.

### PR DESCRIPTION
**Pull request by martinheidegger**
Fixes #5 , based on #3 

After finishing the work on sodium-javascript for react-native we can finally drop old baggage and move the crypto system to a synchronous API without the setup effort.

@consento-org/maintainer

### CODE REVIEW

**Comment by RangerMauve** [comment]
It's a bit hard to know exactly what changed because a lot of the changes are also in other PRs. 😅

**Comment by martinheidegger** [comment]
Since #3 is merged, it would be good to rebase this PR to see the changes more clearly

**Comment by martinheidegger** [comment]
@RangerMauve rebased for easier readability

**Review by RangerMauve — APPROVED** [review]
Looks good! Just read through the code and ran the tests and it seems to be passing.

We should probably hold off on merging until after my final pr to sodium-javascript gets merged. 😁 https://github.com/sodium-friends/sodium-javascript/pulls

**Comment by martinheidegger** [comment]
We have established that sodium-javascript _can_ run on mobile devices, now its just a matter of proper setup the right library. I am fine with merging as-is.

**Pull request merged**
